CREATE TABLE country(
                        country_id bigint generated by default as identity primary key ,
                        country_name varchar(255),
                        continent varchar(255)
);

CREATE TABLE host(
                     host_id bigint generated by default as identity primary key ,
                     host_name varchar(255),
                     host_surname varchar(255),
                     c_id bigint references country(country_id)
);

CREATE TABLE accommodation(
                              accommodation_id bigint generated by default as identity primary key ,
                              accommodation_name varchar(255) NOT NULL,
                              category varchar(255) NOT NULL,
                              host_id bigint references host(host_id),
                              numRooms integer,
                              rented boolean default false
);

